env:
  es2021: true
  node: true
  jest: true
extends: 
  - "eslint:recommended"
  - "@babel/core"
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false
  ecmaFeatures:
    globalReturn: false
  babelOptions:
    babelrc: false
    configFile: false
    presets:
      - "@babel/preset-env"
rules: {}
